name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JSK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name:
          uses: actions/cache@v1
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}

      - name: Run test
        run: mvn -b test