#Workflow name
name: CI/CD Pipeline
on:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
jobs:
  #Test's job
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Maven packages
        run: mvn -B package --file pom.xml

      - name: Run test
        run: mvn -B test

      - name: Build application
        run: mvn clean install
